<?php

namespace App\Enums\Enums;

enum Education: string
{
    case NO_SCHOOLING = 'TIDAK/BELUM SEKOLAH';
    case ELEMENTARY_OR_EQUIVALENT = 'TAMAT SD/SEDERAJAT';
    case JUNIOR_HIGH_OR_EQUIVALENT = 'SLTP/SEDERAJAT';
    case SENIOR_HIGH_OR_EQUIVALENT = 'SLTA/SEDERAJAT';
    case DIPLOMA_I_II = 'DIPLOMA I/II';
    case ACADEMY_DIPLOMA_III_ASSOCIATE = 'AKADEMI/DIPLOMA III/SARJANA MUDA';
    case DIPLOMA_IV_BACHELOR = 'DIPLOMA IV/STRATA I';
    case MASTER_DEGREE = 'STRATA II';
    case DOCTORATE_DEGREE = 'STRATA III';
}
