name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Login ke Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Login ke Azure Container Registry
      - name: Login to Azure Container Registry
        run: |
          docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          -u ${{ secrets.REGISTRY_USERNAME }} \
          -p ${{ secrets.REGISTRY_PASSWORD }}

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/kopsy-app:${{ github.sha }} .

      # Push image ke Azure Container Registry
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/kopsy-app:${{ github.sha }}

      # Deploy ke Azure Web App
      - name: Deploy Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEBAPP_NAME }}
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/kopsy-app:${{ github.sha }}